apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: phone
  name: phone
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: phone
status:
  loadBalancer: {}
