// flow-typed signature: 017a8471f135889cafcf07dcfb9d3c18
// flow-typed version: <<STUB>>/webpack-cleanup-plugin_v^0.5.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cleanup-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cleanup-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cleanup-plugin/lib/getFiles' {
  declare module.exports: any;
}

declare module 'webpack-cleanup-plugin/lib/WebpackCleanupPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cleanup-plugin/lib/getFiles.js' {
  declare module.exports: $Exports<'webpack-cleanup-plugin/lib/getFiles'>;
}
declare module 'webpack-cleanup-plugin/lib/WebpackCleanupPlugin.js' {
  declare module.exports: $Exports<'webpack-cleanup-plugin/lib/WebpackCleanupPlugin'>;
}
