import axios from 'axios'
import {resolve} from 'path'
import {createWriteStream} from 'fs'
const projectRoot = resolve(__dirname, '../../')
const destination = resolve(projectRoot, './configs/gulpGenerated/messageTypes.js')
const warningMessage = '// Don\'t modify this file\n// This file is auto generated by gulp task "\metaData"\n'

exports.getMessageTypes = function() {
  return axios(process.env.HTTP_ENDPOINT + '/getMessageTypes').then(response => {
    let stream = createWriteStream(destination)
    stream.on('close', () => {
      console.log('Message types updated')
    })
    stream.write(warningMessage)
    stream.write(`export default ${JSON.stringify(response.data)}`)
  })
    .catch(e=>{
      throw new Error(e, 'make sure the server is up and check the endpoint variable in .env file')
    })
}
