const {resolve} = require('path')
const {readdirSync, createWriteStream, watch} = require('fs')

const projectRoot = resolve(__dirname, '../../')
const modulePath = resolve(projectRoot, './modules')
const routeFilePath = resolve(projectRoot, './configs/gulpGenerated/routes.js')
const exculdedModuleNames = [
  'Layout',
  'Routers',
  'Shared',
].concat('|')
const warningMessage = '// Don\'t modify this file\n// This file is auto generated by gulp task "watchComponentsAndGenerateRouters"\n'

function getComponentsFromDirectory() {
  const dirsArray = readdirSync(modulePath)
  return dirsArray.filter((dirname) => {
    return exculdedModuleNames.indexOf(dirname) === -1
  })
}

function watchComponents(done) {
  watch(
    modulePath,
    {read: false},
    (event, filename) => {
      generateRouters()
    }
  )
  done()
}

function generateRouters(done) {
  const dirs = '\'' + getComponentsFromDirectory().join('\', \'') + '\''
  let stream = createWriteStream(routeFilePath)
  stream.on('close', () => {
    console.log('Router file updated')
    if (done) {
      done()
    }
  })
  stream.write(warningMessage)
  stream.write('export default [')
  stream.write(dirs + '')
  stream.end(']\n')
}

module.exports = {
  watchComponents,
  generateRouters,
}
