version: '2'

services:
  phone:
    image: 'asia.gcr.io/pg-us-e-app-518137/phone:prod'
    ports:
      - "80:8080"
    command: ["ls", "/app"]
  backend:
    image: 'asia.gcr.io/pg-us-e-app-518137/backend:prod'
    ports:
      - "80:8080"
    command: ["ls", "/app"]
