version: "3.3"

services:
  loopback:
    restart: always
    ports:
      - "8090:8090"
    build:
      context: ../
      dockerfile: configs/docker.prod.nodejs
      args:
        SERVICE_NAME: loopback
    image: loopback
    environment:
      WEB_DB_HOST: postgres
      WEB_DB_PASSWORD: example
    networks:
      - backend
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: webDB
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - backend
    volumes:
      - "webDB:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - "8100:8080"

volumes:
  webDB:
    external: true

networks:
  frontend:
  backend:
