version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_role_arn: ecsTaskExecutionRole
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 256
    mem_limit: 512
  services:
    postgres:
      cpu_shares: 0.3
      mem_limit: 128
      mem_reservation: 32
    loopback:
      essential: false
      cpu_shares: 0.3
      mem_limit: 128
      mem_reservation: 32

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-04c6feedbc9e12f69
        - subnet-0cca913b159cf2984
      security_groups:
        - sg-0242674ce0fe54df7
      assign_public_ip: ENABLED
